apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: my-deployment
    template:
        metadata:
            labels:
                app: my-deployment
        spec:
            containers:
            - name: webapp
              image: chapin/docker-demo:2.0.0
              ports:
              - name: webapp-port
                containerPort: 3000
              livenessProbe:
                  httpGet:
                      path: /
                      port: webapp-port
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  successThreshold: 1
                  failureThreshold: 3


