apiVersion: v1
kind: Pod
metadata:
    name: my-pod
    labels:
        app: webserver
        tier: backend
    annotations:
        version: latest
        release_data: 2018/05/29
        contact: chapin@gmail.com
spec:
    containers:
    - name: pod-demo
      image: chapin/docker-demo:2.0.0
      ports:
      - containerPort: 3000
      env:
      - name: SECRET_USERNAME
        valueFrom:
            secretKeyRef:
                name: demo-secret-from-yaml
                key: username
      - name: SECRET_PASSWORD
        valueFrom:
            secretKeyRef:
                name: demo-secret-from-yaml
                key: password
    nodeSelector:
        hardware: high-memory
